apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: auth-engine
    app.kubernetes.io/name: auth-engine
  name: auth-engine
  namespace: auth-engine-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth-engine
  namespace: auth-engine-system
rules:
- apiGroups:
  - ghippo.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-engine
  namespace: auth-engine-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth-engine
subjects:
- kind: ServiceAccount
  name: auth-engine
  namespace: auth-engine-system