apiVersion: v1
kind: Service
metadata:
  name: auth-engine
  namespace: auth-engine-system
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8888         # Service 端口
    targetPort: 8888   # Pod 监听的端口
  selector:
    app: auth-engine
  type: NodePort
